version: '2'

services:
  eureka-server:
    container_name: eureka-server
    image: ayeshawaheed7/eureka-server:latest
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - shared-network
    depends_on:
      - otel-collector

  apigateway:
    container_name: apigateway
    image: ayeshawaheed7/customer-management-apigateway:9965172f946b467a38feaa31d6ce974f976660fd
    ports:
      - "9093:9093"
    networks:
      - shared-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - otel-collector
      - eureka-server

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - shared-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - shared-network

  kafka-ui:
    image: provectuslabs/kafka-ui:master
    container_name: kafka-ui
    ports:
      - "8090:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    networks:
      - shared-network

  kafka-topics:
    container_name: kafka-topics
    image: ayeshawaheed7/customer-management-kafka-topics:270ff11639a61518375ea358cc7a2a976feef941
    ports:
      - "9094:9094"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - shared-network
    depends_on:
      - kafka

  postgres-customer:
    container_name: postgres-customer
    image: postgres
    environment:
      POSTGRES_USER: ayeshascode
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-customer-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - shared-network
    restart: unless-stopped

  postgres-fraud:
    container_name: postgres-fraud
    image: postgres
    environment:
      POSTGRES_USER: ayeshascode
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-fraud-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - shared-network
    restart: unless-stopped

  postgres-notification:
    container_name: postgres-notification
    image: postgres
    environment:
      POSTGRES_USER: ayeshascode
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-notification-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - shared-network
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - shared-network
    restart: unless-stopped

  customer:
    container_name: customer
    image: ayeshawaheed7/customer-management-customer-service:b197e5d570155dbcbbde1e5b8c97aca218c0543c
    ports:
      - "9090:9090"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - shared-network
    depends_on:
      - postgres-customer
      - otel-collector
      - eureka-server
      - apigateway
      - kafka
      - kafka-topics

  fraud:
    container_name: fraud
    image: ayeshawaheed7/customer-management-fraud-service:b197e5d570155dbcbbde1e5b8c97aca218c0543c
    ports:
      - "9091:9091"
    networks:
      - shared-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres-fraud
      - otel-collector
      - eureka-server

  notification:
    container_name: notification
    image: ayeshawaheed7/customer-management-notification-service:b197e5d570155dbcbbde1e5b8c97aca218c0543c
    ports:
      - "9095:9095"
    networks:
      - shared-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres-notification
      - otel-collector
      - kafka
      - kafka-topics

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - shared-network

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:latest
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./infra/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4318:4318"
    depends_on:
      - zipkin
    networks:
      - shared-network

networks:
  shared-network:
    driver: bridge

volumes:
  postgres-customer-data:
  postgres-fraud-data:
  postgres-notification-data:
  pgadmin:
  zookeeper-data:
  kafka-data:


