services:
  eureka-server:
    container_name: eureka-server
    image: ayeshawaheed7/eureka-server:latest
    ports:
      - "8761:8761"

  postgres-customer:
    container_name: postgres-customer
    image: postgres
    environment:
      POSTGRES_USER: ayeshascode
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-customer-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  postgres-fraud:
    container_name: postgres-fraud
    image: postgres
    environment:
      POSTGRES_USER: ayeshascode
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-fraud-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - postgres
    restart: unless-stopped

  postgres-notification:
    container_name: postgres-notification
    image: postgres
    environment:
      POSTGRES_USER: ayeshascode
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-notification-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres-customer-data:
  postgres-fraud-data:
  postgres-notification-data:
  pgadmin:
