server:
  port: 9096

spring:
  application:
    name: notification
  datasource:
    url: jdbc:postgresql://postgres-notification:5434/notification
    username: ayeshascode
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  kafka:
    bootstrap-servers: kafka:29092
    security-protocol: PLAINTEXT
    consumer:
      notification-updates:
        offset: earliest

otel:
  exporter:
    otlp:
      endpoint: http://otel-collector:4318