name: Auto Approve and Merge My PRs

on:
  workflow_run:
    workflows: ["Build and Publish Docker Image"]
    types:
      - completed

jobs:
  approve-and-merge:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GitHub CLI
        uses: gh-actions/gh-cli@v1

      - name: Authenticate GitHub CLI
        run: gh auth login --with-token <<< ${{ secrets.GITHUB_TOKEN }}

      - name: Check PR author
        id: check_author
        run: |
          MY_GITHUB_USERNAME="ayeshawaheed7"

          PR_AUTHOR=$(gh pr view ${{ github.event.pull_request.number }} --json author --jq '.author.login')
          
          if [ "$PR_AUTHOR" = "$MY_GITHUB_USERNAME" ]; then
            echo "is_author=true" >> $GITHUB_ENV
          else
            echo "is_author=false" >> $GITHUB_ENV
          fi

      - name: Approve and merge my PR
        if: env.is_author == 'true'
        run: |
          # Approve the PR
          gh pr review ${{ github.event.pull_request.number }} --approve

          # Merge the PR
          gh pr merge ${{ github.event.pull_request.number }} --merge --admin
          echo "PR #${{ github.event.pull_request.number }} has been approved and merged"
