name: Build and Publish docker image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    services:
      postgres:
        image: postgres:13.1
        env:
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set Environment Variables
        run: |
          echo "POSTGRES_DB=customer" >> $GITHUB_ENV
          echo "POSTGRES_USER=ayeshascode" >> $GITHUB_ENV
          echo "POSTGRES_PASSWORD=password" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/customer" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_USERNAME=ayeshascode" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_PASSWORD=password" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify -f pom.xml

      - name: Packaging workflow data as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: customer-jar
          path: customer/target/*.jar
          retention-days: 1

